//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabAgeDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSurveyResult
    {
        public int EmployeeSurveyID { get; set; }
        public int EmployeeID { get; set; }
        public int CategoryID { get; set; }
        public int Rating { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
