//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabAgeDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLocation
    {
        public int EmployeeLocationID { get; set; }
        public int EmployeeID { get; set; }
        public System.Data.Entity.Spatial.DbGeography EmployeeGeoLocation { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
